### ISSUE TITLE
Features in ThryAvatarImporter should be optional

### ISSUE THREAD

**Issue by lukis101** [Thryrallo/ThryVRCTools#1]
Got this for Account Switcher but just spent some time getting really confused why fbx material import was getting forced to use external materials instead of embedded ones - which allows remapping materials and prevents them getting shuffled after updating fbx.

**Comment by Thryrallo** [comment]
tools have been split off into separate addons long ago. 
The only one standing at this point is account switcher.

... also i should really check my github issues more
